### ISSUE TITLE
Cannot set interval greater than 260

### ISSUE THREAD

**Issue by fabianluque** [junalmeida/homeassistant-addons#19]
First of all, thanks so much for creating this awesome add-on. As the docs say, camera setup is a little tricky but once you get it the readings are very reliable. 

I was trying to set a larger interval of 5 minutes (300 seconds) for my gas meter but I noticed the current max is 260. 

Is it possible to increase it?

**Comment by junalmeida** [comment]
Possible it is, but could you elaborate on why do you think you need more time? 
I just wanted to know about scenarios I couldn't anticipate. Thank you

**Comment by fabianluque** [comment]
@junalmeida Gas meter usually does not move too fast due to the consumption pattern I have at home so it does not make sense to take a snapshot so often. It's more of an optimization thing, nothing is wrong with calling it more often.

**Comment by fabianluque** [comment]
Thank you! Works great!
