### ISSUE TITLE
Request: add a limit parameter in configuration

### ISSUE THREAD

**Issue by Sheugel** [junalmeida/homeassistant-addons#23]
Hi,
I sometimes get invalid readings due to bad focusing of my camera or no new reading following a problem with my camera server.
As a result, it can happen that the next good reading is above the 3 kWh limit of the addon to accept the value.
Would it be possible to let the user define the limit?
Thanks

**Comment by junalmeida** [comment]
Totally, yes. It is interesting that when I first introduced that limit is what makes a good parameter and I came to no-good bullet-proof answer so a new parameter makes total sense.

**Comment by Sheugel** [comment]
Thanks!

**Comment by Sheugel** [comment]
Hey, may I ask you if there is any progress on this? Thanks!

**Comment by junalmeida** [comment]
Nope, not yet.
