### ISSUE TITLE
Request: add error logs to Home Assistant system logs

### ISSUE THREAD

**Issue by Sheugel** [junalmeida/homeassistant-addons#26]
### What happened?

Hi,
I would like to be able to use the error logs of the addon in order to trigger an automation: take another snapshot of the counter(s) to get a good quality picture (in case of invalid reading or Aruco markers not found).
I think for that I need to use the Home Assistant system logs but the logs of the addons don't appear there.
Would it be possible to send the logs to the HA system logs?
Thanks

### AddOn and Version

meterparser-1.0.1.1

### HomeAssistant Version

2022.5.5

### Relevant log output

```shell
igits_gvision.night-meter 2022-06-11 12:01:39 PM - ERROR     
Not a valid OCR result: E20900\n
app.camera.night-meter    2022-06-11 12:01:39 PM - ERROR     
Invalid reading - current=0.0, previous=6022.0, limit=6025.0 - Value could be too high or less than previous reading.
igits_gvision.night-meter 2022-06-11 01:02:29 PM - ERROR     
Not a valid OCR result: ៤០ ០ ៛ ០ 2 ឃុំ\n
app.camera.night-meter    2022-06-11 01:02:29 PM - ERROR     
Invalid reading - current=0.0, previous=6022.0, limit=6025.0 - Value could be too high or less than previous reading.
app.camera.night-meter    2022-06-11 02:04:12 PM - ERROR     
Could not find ArUco markers. Please print two markers at https://chev.me/arucogen/ and stick to the top-left and bottom-right corners of the region of interest. If markers are already there check your camera's light conditions and quality.
app.camera.night-meter    2022-06-11 02:09:26 PM - ERROR     
Could not find ArUco markers. Please print two markers at https://chev.me/arucogen/ and stick to the top-left and bottom-right corners of the region of interest. If markers are already there check your camera's light conditions and quality.
app.camera.night-meter    2022-06-11 02:14:41 PM - ERROR     
Could not find ArUco markers. Please print two markers at https://chev.me/arucogen/ and stick to the top-left and bottom-right corners of the region of interest. If markers are already there check your camera's light conditions and quality.
```

**Comment by junalmeida** [comment]
I'm not sure if it is possible to redirect logs, however I can take a look if it is possible to fire an event (go to dev tools, events tab). But this is a repetitive pooling task, so even if it fails, it will try to take another snapshot again on its own in some minutes. I'd like to understand more about what you are trying to accomplish.  

If you check: 

https://github.com/junalmeida/homeassistant-addons/blob/1dc57035b8e26a629450a9af6f11f1ac447df67e/meterparser/src/app/camera.py#L82-L98

you may see it tries to take a snapshot 5 times each 10 secs before giving up and logging an error.

**Comment by Sheugel** [comment]
Thanks for your reply.
For more clarity, here is my setup: I use the Android IP Webcam app on an old Galaxy S4 (with Lineage OS). The S4 is on a tripod in front of my counter which is in a sealed plastic box/container in a "technical room" in the basement of my house (where there is no day light).
If I use the flash,  the picture qaulity is quite bad (ao due to the reflection of the flash on the box). I tested with the snapshot taken by the addon and I get an error.
To have a more or less good picture, I make an automation to turn on the lights of the technical room, take a snapshot and turn off the lights. I have 2 automations, one to take a snapshot for the day meter (every hour during the day in the week) and another for the night/offpeak meter (every hour during the night and the weekend). The url provided to the Meter Parser addon is the url of the taken snapshot (one for the day meter and the other for the night meter).
I hope it makes my request clearer...
Thanks

**Comment by Sheugel** [comment]
That would be a good solution to be able, like you say, to fire an event to set an automation to turn on the flash secs before taking a snapshot, then off.
