### ISSUE TITLE
getting "Invalid width and height" error in log

### ISSUE THREAD

**Issue by gdlesage** [junalmeida/homeassistant-addons#3]
my config is as follows:

cameras:
  - snapshot_url: http://192.168.1.208/gas/gas_meter.jpg
    name: Gas Meter
    interval: 60
    device_class: gas
    dials:
      - CCW CW CCW CW
    unit_of_measurement: m³
    dial_size: 200
mqtt:
  host: 192.168.1.208
  username: user
  password: password
  port: 1883
log_level: INFO

log output shows error "Invalid width and height".  I am not sure if that is referring to gas_meter.jpg image size which is1280X960 (960P) or something else.  I have seen other errors but they were correctible by changing camera distance and/or ArUco markers.  Complete log output below.  Any thoughts?

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Meter Parser
 Read meter needles and numbers from a camera snapshot.
-----------------------------------------------------------
 Add-on version: 1.0.0.21
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.12.4
 Home Assistant Supervisor: 2022.01.0

 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
app.camera.gas-meter      2022-01-31 11:35:39 PM - INFO      
Starting camera Gas Meter
app.camera.gas-meter      2022-01-31 11:35:39 PM - INFO      
Listening to messages at topic homeassistant/sensor/d000fcfb-meter-parser/gas-meter/set
app.camera.gas-meter      2022-01-31 11:36:31 PM - ERROR     
Invalid width and height
app.camera.gas-meter      2022-01-31 11:37:31 PM - INFO      
Listening to messages at topic homeassistant/sensor/d000fcfb-meter-parser/gas-meter/set
app.camera.gas-meter      2022-01-31 11:38:24 PM - ERROR     
Invalid width and height
app.camera.gas-meter      2022-01-31 11:39:24 PM - INFO      
Listening to messages at topic homeassistant/sensor/d000fcfb-meter-parser/gas-meter/set

**Comment by gdlesage** [comment]
Invalid width and height error was due to my error using the identical ArUco images, they need to be different as implied in instructions.  Below is test showing reading from the two faster two moving dials (2 and 0.5 cf) which with dial pointer movement gives me a reading of 7.0.  
![Screenshot (23)](https://user-images.githubusercontent.com/14796404/152647847-b24c1c38-a4cf-448a-ab08-2a11022c6fc9.png)

**Comment by junalmeida** [comment]
Hmm interesting. I will add a check to show a meaningful error message. Thanks for pointing that out, and yes they need to be different and placed left-to-right, top-to-bottom aligned. 

But is the reading of 7.0 correct? Btw if your measurement is cubic feet you may change `unit_of_measument`. And thank you for trying out this addon. Have in mind this is on its very very early stages.

**Comment by junalmeida** [comment]
Ah, I just realized that you have two dials on your image, but 4 dials on your yaml.

**Comment by junalmeida** [comment]
81459cc5423f245b02cc0fe39b0426d053ee6a32

**Comment by gdlesage** [comment]
yes image above is just a test, in  first image the right dial read little above zero and in the second image right dial read 7, so the output of seven after reading second image seems correct.  going to test camera on meter this afternoon, with the four dials.  I assume I need to leave  ArUco markers on meter permanently

**Comment by junalmeida** [comment]
Yes, the ArUco marks helps to get and rotate automatically only the region of interest to be parsed in case of camera moving slightly. Should be there permanently.
