### ISSUE TITLE
[Bug]: Error parsing gas meter reading

### ISSUE THREAD

**Issue by fabianluque** [junalmeida/homeassistant-addons#54]
### What happened?

![7F3DD121-058C-4CCB-BC4C-5C19600F459A](https://user-images.githubusercontent.com/5721029/212214943-7f5733b1-5e82-42e1-bdaa-091044b1dc49.jpeg)

Gas meter is about to get to 7000 (as you can see in the image) and it seems the add on is having issues parsing the current value. It seems to be introducing a dash after the first digit (as you can see in the logs I shared)

Please let me know if you need any more info.  

### AddOn and Version

meterparser-1.0.2.5

### HomeAssistant Version

2023.1.1

### Relevant log output

```shell
06:15:22 PM - ERROR     
could not convert string to float: '7-199'
app.camera.gas-meter      2023-01-12 06:20:23 PM - ERROR     
could not convert string to float: '6-199'
```

**Comment by fabianluque** [comment]
I’ve downgraded to 1.0.2.1 just to check if it was a bug recently introduced but the error is still happening.

**Comment by junalmeida** [comment]
Ok thanks for reporting! Based on your image and logs it seems it had trouble reading the second. The latest changes only affects digits meters, dials code was not touched intentionally. 

Is it possible to improve the image quality a bit by adjusting your camera? Maybe moving or tilting it slightly would be enough. I can see some distortions on this image that could be related to the camera axis.

**Comment by fabianluque** [comment]
Yes, I can try adjusting a little, always tricky as you know. This setup has been working fine for months, it only starting showing the error when it was closed to 7000. To add more, now the meter is past 7000 and the add-on seems to be working mostly fine again.

Is it possible to remove unwanted characters before parsing? If it's reading dials, should only be numbers in that string. Or are dashes possible too?

**Comment by junalmeida** [comment]
Indeed dashes are not expected, however removing the dash does not fix it, because even if I removed the dash in the middle, there is no reading and the result would be the same: an invalid reading. 

Given that you have good readings now, I'm considering this as an expected scenario due to bad lighting conditions and/or camera angle. I don't see evidence that the 7000 reading would always fail, seems like just a coincidence.
