### ISSUE TITLE
[Bug]: Error prevents Meter Parser to continue reading the meter

### ISSUE THREAD

**Issue by fabianluque** [junalmeida/homeassistant-addons#56]
### What happened?

It seems the add-on fails while downloading the image from the camera. When that happens, it never tries to take a reading anymore requiring a restart. 

After restart, add-on works just fine. 

### AddOn and Version

meterparser-1.0.2.5

### HomeAssistant Version

2023.1.7

### Relevant log output

```shell
('Connection broken: IncompleteRead(44453 bytes read, 81674 more expected)', IncompleteRead(44453 bytes read, 81674 more expected))
```

**Comment by junalmeida** [comment]
Interesting. Current code executes `get_image` on a `try/except` block, and retries at least 5 times. Even if it fails for 5 times, the loop is supposed to continue. 
So, I'm wondering if maybe you ran under a very catastrophic scenario (like memory overflow)?

For this one I think I'm going to need more stack trace. Please enable `log_level: DEBUG` to provide more information on this problem.

**Comment by junalmeida** [comment]
You can also try changing method from HTTP to FFMPEG. 
`force_ffmpg: True # Force use of ffmpeg on http urls (optional, default False)`

**Comment by fabianluque** [comment]
Yes, very strange. I have added the log_level setting. Will report back when it happens again.
